@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados

###

GET {{baseUrl}}/recados/
?limit=10
&offset=10

###
GET {{baseUrl}}/recados/2
###

POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Um texto longo",
  "deId": 12,
  "paraId": 12
  
}
###

PATCH  {{baseUrl}}/recados/3
Content-Type: application/json

{
}

###
DELETE {{baseUrl}}/recados/2

### EXEMPLO DE ROTA
### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}

### ConceitosManualController Home

# @name ConceitosManualControllerHome

GET {{baseUrl}}/conceitos-manual


### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome

GET {{baseUrl}}/conceitos-automatico


# Pessoas
###
GET {{baseUrl}}/pessoas

###

GET {{baseUrl}}/pessoas/
?limit=10
&offset=10

###
GET {{baseUrl}}/pessoas/2
###

POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "email":"email1@email.com",
  "password":"123456",
  "nome": "rafael"
}
###

PATCH  {{baseUrl}}/pessoas/12
Content-Type: application/json

{
  "nome": "outro"
}

###
DELETE {{baseUrl}}/pessoas/9

