@baseUrl = http://localhost:3000

# RECADOS
###
GET {{baseUrl}}/recados

###

GET {{baseUrl}}/recados/
?limit=10
&offset=10

###
GET {{baseUrl}}/recados/2
###

POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Um texto longo",
  "de": "Joana",
  "para": "João"
}
###

PATCH  {{baseUrl}}/recados/3
Content-Type: application/json

{
}

###
DELETE {{baseUrl}}/recados/2

### EXEMPLO DE ROTA
### AppControllerGetHello

# @name AppControllerGetHello

GET {{baseUrl}}

### ConceitosManualController Home

# @name ConceitosManualControllerHome

GET {{baseUrl}}/conceitos-manual


### ConceitosAutomaticoController Home

# @name ConceitosAutomaticoControllerHome

GET {{baseUrl}}/conceitos-automatico

